apiVersion: v1
kind: ConfigMap
metadata:
  name: trigger-ga-script
  namespace: ghz
data:
  trigger_workflow.sh: |
    NOW=$( date +%s )
    IAT="${NOW}"
    # expire 9 minutes in the future. 10 minutes is the max for github
    EXP=$((${NOW} + 540))
    HEADER_RAW='{"alg":"RS256"}'
    HEADER=$( echo -n "${HEADER_RAW}" | openssl base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n' )
    PAYLOAD_RAW='{"iat":'"${IAT}"',"exp":'"${EXP}"',"iss":'"${GITHUB_APP_ID}"'}'
    PAYLOAD=$( echo -n "${PAYLOAD_RAW}" | openssl base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n' )
    HEADER_PAYLOAD="${HEADER}"."${PAYLOAD}"
    SIGNATURE=$( openssl dgst -sha256 -sign <(echo -n "${PEM}") <(echo -n "${HEADER_PAYLOAD}") | openssl base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n' )
    JWT=${HEADER_PAYLOAD}.${SIGNATURE}
    CONTENT=$(curl -X POST -H "Authorization: Bearer ${JWT}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/app/installations/"${GITHUB_APP_INSTALLATION_ID}"/access_tokens)
    TOKEN=$(jq -r '.token' <<<"$CONTENT")

    curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $TOKEN" https://api.github.com/repos/"${REPO_OWNER}"/"${REPO_NAME}"/dispatches -d '{"event_type":'"${EVENT_TYPE}"',"client_payload":{"unit":false,"integration":true}}'
  REPO_OWNER: semutmerah
  REPO_NAME: go-grpc
  EVENT_TYPE: on-demand-test
