apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: grpc-server
  namespace: ghz
spec:
  selector:
    matchLabels:
      app: server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: semutmerah/go-grpc:latest
        imagePullPolicy: Always
        name: go-grpc
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
