apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  labels:
    app: server
spec:
  ports:
    - name: grpc
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: server
