apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: ghz
  generateName: test-job-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
      - name: config-volume
        configMap:
          name: trigger-ga-script
          defaultMode: 0777
      containers:
      - name: jwt-tools
        image: semutmerah/jwt-tools:latest
        command: ["/bin/bash", "-c"]
        args: ["/script/trigger_workflow.sh"]
        volumeMounts:
        - mountPath: /script
          name: config-volume
        env:
        - name: PEM
          valueFrom:
            secretKeyRef:
              name: github-app-private-key
              key: private_key.pem
              optional: false
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              name: github-app-private-key
              key: GITHUB_APP_ID
              optional: false
        - name: GITHUB_APP_INSTALLATION_ID
          valueFrom:
            secretKeyRef:
              name: github-app-private-key
              key: GITHUB_APP_INSTALLATION_ID
              optional: false
        - name: REPO_OWNER
          valueFrom:
            configMapKeyRef:
              name: trigger-ga-script
              key: REPO_OWNER
        - name: REPO_NAME
          valueFrom:
            configMapKeyRef:
              name: trigger-ga-script
              key: REPO_NAME
        - name: EVENT_TYPE
          valueFrom:
            configMapKeyRef:
              name: trigger-ga-script
              key: EVENT_TYPE
  backoffLimit: 4
