apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: ghz
  generateName: test-job-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
      - name: config-volume
        configMap:
          name: trigger-ga-script
          defaultMode: 0777
          items:
          - key: trigger_workflow.sh
            path: script
      containers:
      - name: curl
        image: curlimages/curl
        command: ["/bin/ash", "-c"]
        args: ["/etc/config/script/trigger_workflow.sh"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        env:
        - name: PEM
          valueFrom:
            secretKeyRef:
              name: github-app-private-key
              key: private_key.pem
              optional: false
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              name: github-app-private-key
              key: GITHUB_APP_ID
              optional: false
        - name: GITHUB_APP_INSTALLATION_ID
          valueFrom:
            secretKeyRef:
              name: github-app-private-key
              key: GITHUB_APP_INSTALLATION_ID
              optional: false
        - name: REPO_OWNER
          valueFrom:
            configMapKeyRef:
              name: trigger-ga-script
              key: REPO_OWNER
        - name: REPO_NAME
          valueFrom:
            configMapKeyRef:
              name: trigger-ga-script
              key: REPO_NAME
  backoffLimit: 4
