apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: ghz
  generateName: test-job-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command: ["/bin/sh", "-c", "echo 'Halo semua'"]
      restartPolicy: Never
  backoffLimit: 4
