name: Test repository dispatch

on:
  repository_dispatch:
    types: [post-deployment-job]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: |
          echo "Yeay bisa akhirnya"
